language: rust
rust:
  - stable
  - beta
  - 1.34.0
before_script:
  - rustup component add clippy
script:
  - cargo build --verbose --all --all-features
  - cargo clippy --all --all-features -- -D warnings
  - cargo test --verbose --all --all-features
