[package]
name = "rpki"
version = "0.2.0"
authors = ["The NLnet Labs RPKI Team <rpki@nlnetlabs.nl>"]
description = "A library for validating and creating RPKI data."
repository = "https://github.com/NLnetLabs/rpki-rs"
keywords = ["rpki", "routing-security"]
categories = ["network-programming"]
license = "BSD-3-Clause"

[dependencies]
base64          = "^0.9"
bcder           = "^0.1"
bytes           = "^0.4"
chrono          = "^0.4"
failure         = "^0.1"
hex             = "^0.3"
log             = "^0.4"
openssl         = { version = "^0.10", optional = true }
ring            = "^0.13"
untrusted       = "^0.6"
xml-rs          = "^0.8"

[features]
default = []
softkeys = [ "openssl" ]
extra-debug = [ "bcder/extra-debug" ]
