[package]
name = "rpki"
version = "0.1.0"
authors = [
    "Tim Bruijnzeels <tim@nlnetlabs.nl>",
    "Martin Hoffmann <martin@nlnetlabs.nl>"
]

[dependencies]
base64          = "^0.9"
bytes           = "^0.4"
chrono          = "^0.4"
failure         = "^0.1"
hex             = "^0.3"
log             = "^0.4"
openssl         = { version = "^0.10", optional = true }
ring            = "^0.13"
untrusted       = "^0.6"
xml-rs          = "^0.8"

[dependencies.ber]
git = "https://github.com/NLnetLabs/ber-rs.git"

[features]
default = []
softkeys = [ "openssl" ]
extra-debug = [ "ber/extra-debug" ]
