[package]
name = "rpki"
version = "0.1.0"
authors = [
    "Tim Bruijnzeels <tim@nlnetlabs.nl>",
    "Martin Hoffmann <martin@nlnetlabs.nl>"
]

[dependencies]
base64          = "^0.9"
ber             = { git="https://github.com/NLnetLabs/ber-rs.git" }
bytes           = "^0.4"
chrono          = "^0.4"
failure         = "^0.1"
log             = "^0.4"
untrusted       = "^0.6"
xml-rs          = "^0.8"

[dependencies.ring]
version  = "^0.13"
features = ["rsa_signing"]
